
package soapClient;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "InventoryServiceV2", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/", wsdlLocation = "https://dsstandardtest.hitpromo.net/inventoryV2RC4")
public class InventoryServiceV2
    extends Service
{

    private final static URL INVENTORYSERVICEV2_WSDL_LOCATION;
    private final static WebServiceException INVENTORYSERVICEV2_EXCEPTION;
    private final static QName INVENTORYSERVICEV2_QNAME = new QName("http://www.promostandards.org/WSDL/Inventory/2.0.0/", "InventoryServiceV2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://dsstandardtest.hitpromo.net/inventoryV2RC4");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        INVENTORYSERVICEV2_WSDL_LOCATION = url;
        INVENTORYSERVICEV2_EXCEPTION = e;
    }

    public InventoryServiceV2() {
        super(__getWsdlLocation(), INVENTORYSERVICEV2_QNAME);
    }

    public InventoryServiceV2(WebServiceFeature... features) {
        super(__getWsdlLocation(), INVENTORYSERVICEV2_QNAME, features);
    }

    public InventoryServiceV2(URL wsdlLocation) {
        super(wsdlLocation, INVENTORYSERVICEV2_QNAME);
    }

    public InventoryServiceV2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, INVENTORYSERVICEV2_QNAME, features);
    }

    public InventoryServiceV2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public InventoryServiceV2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns InventoryService
     */
    @WebEndpoint(name = "InventoryServiceBinding")
    public InventoryService getInventoryServiceBinding() {
        return super.getPort(new QName("http://www.promostandards.org/WSDL/Inventory/2.0.0/", "InventoryServiceBinding"), InventoryService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns InventoryService
     */
    @WebEndpoint(name = "InventoryServiceBinding")
    public InventoryService getInventoryServiceBinding(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.promostandards.org/WSDL/Inventory/2.0.0/", "InventoryServiceBinding"), InventoryService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (INVENTORYSERVICEV2_EXCEPTION!= null) {
            throw INVENTORYSERVICEV2_EXCEPTION;
        }
        return INVENTORYSERVICEV2_WSDL_LOCATION;
    }

}
