
package soapClient;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "InventoryService", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface InventoryService {


    /**
     * 
     * @param getFilterValuesRequest
     * @return
     *     returns soapClient.GetFilterValuesResponse
     */
    @WebMethod(action = "getFilterValues")
    @WebResult(name = "GetFilterValuesResponse", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/", partName = "GetFilterValuesResponse")
    public GetFilterValuesResponse getFilterValues(
        @WebParam(name = "GetFilterValuesRequest", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/", partName = "GetFilterValuesRequest")
        GetFilterValuesRequest getFilterValuesRequest);

    /**
     * 
     * @param getInventoryLevelsRequest
     * @return
     *     returns soapClient.GetInventoryLevelsResponse
     */
    @WebMethod(action = "getInventoryLevels")
    @WebResult(name = "GetInventoryLevelsResponse", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/", partName = "GetInventoryLevelsResponse")
    public GetInventoryLevelsResponse getInventoryLevels(
        @WebParam(name = "GetInventoryLevelsRequest", targetNamespace = "http://www.promostandards.org/WSDL/Inventory/2.0.0/", partName = "GetInventoryLevelsRequest")
        GetInventoryLevelsRequest getInventoryLevelsRequest);

}
